apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring
  name: a-spring-hello
spec:
  ports:
  - name: a-spring-hello
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring
  sessionAffinity: None
  type: NodePort

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: spring
  name: a-spring-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - image: master.cfc:8500/default/spring-hello:v1
        imagePullPolicy: Always
        name: a-spring-hello
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
      - name: admin.registrykey